# This configuration builds the repository and runs stress

# Don't run CI for this config
trigger: jkotalik/stressRuns

pool:
    vmImage: 'windows-2019'
variables:
    buildConfiguration: 'Release'
steps:
    - powershell: ./src/Server/Kestrel/stress/build.cmd
    - powershell: .dotnet/dotnet.exe ./src/Server/Kestrel/stress/HttpStress.csproj
